var quiz_data = [ 
  {
        "choices": [
            {
                "feedback": "Let me add new information to help you solve this question. There are 26 possible 1-letter words, 26 &times; 26 2 letter words, 26 &times; 26 &times; 26 3-letter words, and so on.  So there would be 26<sup>N</sup> N-letter words.  This is <i>exponential</i>. ",
                "score": "0",
                "text": "Reasonable Time (polynomial time)"
            },
            {
                "feedback": "Yes. If the string has <i>N</i> letters 'a' to 'z', then there are 26<sup>N</sup> possible strings, which is <i>exponential</i>.  This is similar to trying to crack a long password made up of lowercase letters. In this case, each letter in the password can be one of 26 possible letters.   If you made such a password long enough (e.g., more than 15 letters), it would be fairly secure from brute force attack. ",
                "score": "1",
                "text": "Not a reasonable time (exponential time)"
            }
        ],
        "cspcode": "4.2.1C",
        "description": "Tractable or Intractable",
        "question": "Does the following algorithm run in a reasonable time?   For any length string of letters using any combination of the letters 'a' through 'z', write down all possible strings.",
        "source": "mcsp-5",
        "type": "Mc",
        "heading": "Algorithm Analysis",
        "hint": "Let me add new information to help you solve this question. There are 26 possible 1-letter words, 26 &times; 26 2 letter words, 26 &times; 26 &times; 26 3-letter words, and so on.  So there would be 26<sup>N</sup> N-letter words.  ",
        "wrongfeedback": ""
    },
  { 'choices': [ { 'feedback': 'Symmetric is part of the correct answer! Symmetric encryption uses a single key to encrypt and decrypt.',
                   'score': 0.5,
                   'text': 'Symmetric'},
                 { 'feedback': 'Sorry, alphabetic is not correct. The Vigenere cipher is polyalphabetic (using multiple alphabets).',
                   'score': -1.0,
                   'text': 'Alphabetic'},
                 { 'feedback': 'Sorry, transposition is not correct. Transposition ciphers rearrange the letters in the plaintext message. These ciphers do not do that.',
                   'score': -1.0,
                   'text': 'Transposition'},
                 { 'feedback': 'Substitution is part of the correct answer! Substitution ciphers replace one character for another.',
                   'score': 0.5,
                   'text': 'Substitution'}],
    'cspcode': '6.3.1K',
    'description': 'Substitution cipher examples',
    
    'question': '<i>Caesar</i> cipher, <i>simple substitution</i> cipher, and <i>Vigenere</i> cipher are all examples of __________ ciphers.',
    'source': 'mcsp-7',
    'type': "Ma",
    'heading': 'Encryption',
    'hint': 'These encryption algorithms all replace a character with another character and use a single key to encrypt and decrypt.',
    'wrongfeedback': ''},
  { 'choices': [ { 'feedback': 'A is not correct. When you arrange items or objects you are <i>sorting</i> through them. Therefore, a search algorithm is not appropriate for this problem.',
                   'score': -1.0,
                   'text': 'A. Arranging a deck of cards from the lowest to the highest value cards.'},
                 { 'feedback': "B is correct. A phone book is arranged <i> in order </i> by last name. If you know the person's full name this includes their last name and you can then perform a binary search to find their phone number.",
                   'score': 0.5,
                   'text': "B. Looking up a phone number in the phone book given the person's full (unique) name."},
                 { 'feedback': 'C is correct. A dictionary is arranged <i> in order </i> alphabetically. Thus, a binary search can be used to find any word in a dictionary.',
                   'score': 0.5,
                   'text': 'C. Looking up a word in a dictionary. '},
                 { 'feedback': 'D is not correct. A phone book is arranged in order, but it is in order <i> by last name <i>. In order to solve this problem using a binary search, the phone book would need to be in order by phone number.',
                   'score': -1.0,
                   'text': "D. Looking up a person's name in the phone book given the person's phone number. "},
                 { 'feedback': 'No, A binary search is only appropriate when the collection you are searching is arranged <i>in order </i>.',
                   'score': -1.0,
                   'text': 'Finding the smallest number in a list of numbers arranged randomly. '}],
    'cspcode': '4.2.4H',
    'description': 'Binary Search',
     'heading': 'Search Algorithms',
    'hint': 'Binary search can only be used on sorted data.',
    'question': 'For which of the problems would the <i><b>binary search</b></i> algorithm be useful? <br>Choose all that apply.',
    'source': 'mcsp-5',
    'type': "Ma",
    'wrongfeedback': ''},
  {"choices":[{"feedback":"Sorry, bandwidth involves data as well as time.","score":"0","text":"how fast your computer can connect to the Internet "},{"feedback":"You're very close!","score":"0","text":"the amount of time it takes to send data over the Internet "},{"feedback":"Sorry, bandwidth measures more than just emails.","score":"0","text":"the average length of e-mails that you can send on a daily basis"},{"feedback":"That's right. Bandwidth measures how much data you can send in a given amount of time.","score":"1","text":"the amount of data that can be sent in a fixed amount of time"}],
   "cspcode":"6.2.2J",
   "description":"Bandwidth Definition",
   "question":"Bandwidth measures ___________________. ",
   "source":"mcsp-7",
   "type":"Mc",
   "wrongfeedback":"",
   "hint":"Bandwidth is a measure of bit rate.",
   "heading":"Bandwidth"},
  { "choices":[{"feedback":"Sorry, but the <i>one-time pad</i> has been proved mathematically to be an unbreakable cipher.  The properties of an unbreakable cipher is that is has a completely <i>random key</i> that is as long as its message and that is used only once.","score":"0","text":"True"},{"feedback":"RIght. The <i>one-time pad</i> has been proved mathematically to be an unbreakable cipher.  The properties of an unbreakable cipher is that is has a completely <i>random key</i> that is as long as its message and that is used only once.","score":"1","text":"False"}],"cspcode":"6.3.1","description":"Unbreakable cipher T/F",
   "question":"True or false. There is no such thing as an unbreakable cipher.  No matter what the cipher, analysts will always find a way to break it.",
   "source":"mcsp-7",
   "type":"Mc",
   "hint":"The properties of an unbreakable cipher is that is has a completely <i>random key</i> that is as long as its message and that is used only once.",
   "heading":"Encryption",
   "wrongfeedback":""},
  {"choices":[{"feedback":"Unfortunately the app would probably crash because you did not use a valid index.","score":"0","text":"It would give you the last item in the list. "},{"feedback":"Unfortunately the app would probably crash because you did not use a valid index.","score":"0","text":"It would give you the first item in the list. "},{"feedback":"That's right! When you are referring to an item in a list using an index, you must make sure to use a valid index. For this list, the valid indexes are 1 through 4. Using any other index is sometimes called an Index out of bounds error.","score":"1","text":"It would crash because there is no item with that index. "},{"feedback":"Since there is no index of 4, it would unfortunately probably crash the app because you did not use a valid index.","score":"0","text":"It would ignore your request. "},{"feedback":"Unfortunately the app would probably crash because you did not use a valid index.","score":0,
  "text":"It would give you a random item from the list. "}],
   "cspcode":"5.3.1K",
   "description":"Lists",
   "question":"What would happen if your code asked for the item at index 5 in the list shown here? <apml>list <- [\"Yes\", \"No\", \"Maybe\", \"Unsure\"]</apml>",
   "source":"mcsp-3",
   "type":"Mc",
   "wrongfeedback":"",
   "hint":"Lists are indexed starting at 1.",
   "heading":"Lists"},
 {
     "choices":[{"feedback":"An algorithm is indeed a sequence of precise instructions. So this is not the correct answer.","score":"0","text":"An algorithm is a sequence of precise instructions. "},{"feedback":"Yes, by process of elimation, this is the correct answer.  It has been proved that there are problems for which it is impossible to write a correct algorithm.  Such problems are called <a target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Undecidable_problem\">undecidable problems</a>.  A surprisingly simple example is the <i>halting problem</i>,  which can be stated as:  Given a description of an arbitrary computer program and a finite set of inputs to the program, determine whether the program will eventually stop or run forever.","score":"1","text":"Algorithms can be written to solve every problem. "},{"feedback":"Algorithms do proceed step-by-step.  So this is not the correct answer.","score":"0","text":"Algorithms are step-by-step procedures."},{"feedback":"Algorithms are indeed constructed by combinations of three control structures,  sequence, selection, and repetition.  So this is not the correct answer. ",
 "score":"0",
 "text":"Algorithms consist of a combination of sequences, selections, and/or repetitions. "}],
  "cspcode":"4.2.2D",
  "description":"What an algorithm is not",
  "question":"Which of the following is <b><i>not true</i></b> about algorithms: ",
  "source":"mcsp-5",
  "type":"Mc",
  "wrongfeedback":"",
  "hint":"Are all problems decidable?",
  "heading":"Algorithms"
 },
  {
      "choices":[
      {"feedback":" Let’s go back and try it again. Notice that there are two forwards followed by a turn followed by one forward and so on, so one side is longer than the other.","score":"0","text":"A square "},
              {"feedback":"Let’s go back and try it again. ","score":"0","text":"A right angle "},
              {"feedback":"That's right. This algorithm would draw a rectangle whose length is twice as long as its width. ","score":"1","text":"A rectangle"},{"feedback":"Let’s go back and try it again. ","score":"0","text":"A circle "}],
   "cspcode":"4.1.1B",
   "description":"Algorithm to draw a rectangle",
   "question":"Assuming that forward tells a robot to move forward by 10 pixels and turn tells it to turn right by 90 degrees, what shape would be drawn by this algorithm?  <b>    forward      forward      turn      forward      turn      forward      forward      turn      forward      turn</b>",
   "source":"mcsp-5",
   "type":"Mc",
   "wrongfeedback":"",
   "hint":"Try following the commands in order to draw the shape.",
   "heading":"Algorithms"},
  { 'choices': [ { 'feedback': 'Here are some strategies to figure this out. The programmer should not rebuild their entire app just because there is a bug in it. They should take their time to examine the code and form a hypothesis about what the bug may be. Then they should design and implement an experiment, and then debug and retest their app.',
                   'score': 0.0,
                   'text': 'Rebuild the app and then retest the app '},
                 { 'feedback': "That's right! When debugging a program, a programmer should form a hypothesis about what the bug might be, then design and implement an experiment to test their hypothesis. If their hypothesis was correct, then the programmer should debug the app and retest. If their hypothesis was wrong, the programmer should form a new hypothesis",
                   'score': 1.0,
                   'text': 'Form a hypothesis about what might be wrong, design an experiment to test their hypothesis, perform the experiment, debug, and then retest the app. '},
                 { 'feedback': 'Here are some strategies to figure this out. He/she should form a hypothesis about what could possible be wrong with the code, however, just forming a hypothesis and then retesting the app is not enough.',
                   'score': 0.0,
                   'text': 'Form a hypothesis and then retest the app. '},
                 { 'feedback': 'Here are some strategies to figure this out. It is not recommended that he/she start changing code without first thinking about, and forming an hypothesis, about what could possible be wrong. The programmer should take their time, form a hypothesis, design and implement an experiment, and then debug and retest theirapp.',
                   'score': 0.0,
                   'text': 'Immediately start changing code and retest the app. '}],
    'cspcode': '5.4.1',
    'description': 'Debugging a Program',
    'heading': 'Debugging',
    'question': 'Your classmate discovers that their code has a bug in it. What should she do to debug their app? ',
    'source': 'mcsp-5',
   'hint': 'Think about what would give the best results.',
    'type': "Mc",
    'wrongfeedback': ''},
 {
     "choices":[{"feedback":"That's right! For searching an unordered list the sequential search algorithm is the better choice.  ","score":"1","text":"Sequential search"},{"feedback":"A binary search is only appropriate when the collection you are searching is ordered.","score":"0","text":"Binary search"}],
  "cspcode":"4.2.4H",
  "description":"Choosing a search algorithm",
  "question":"For searching an <i><b>unordered list</b></i>, which search algorithm is the better choice? ",
  "source":"mcsp-5",
  "type":"Mc",
  "wrongfeedback":"",
  "hint":"Will binary search work on an <b>unordered list</b>?",
  "heading":"Search Algorithms"
 },
  {
      "choices":[
      {"feedback":"High-level languages are easier for humans to understand.","score":"0","text":"low-level languages are easier for humans to understand"},
              {"feedback":"This statement would be true of low-level machine languages.  High level languages are designed to make it easy of humans to program the computer. ","score":"0","text":"high-level languages provide abstractions that closely match the machine's architecture."},
              {"feedback":"Correct.  For example, the code you write has to be translated into machine language statements that can be understood by the CPU.  ","score":"1","text":"high-level languages must be translated by software programs into low-level machine languages before they can be run on a computer"},
              {"feedback":"Computers can only understand their own low-level machine language.  Each type of CPU, such as Intel or Motorola, has its own machine language.","score":"0","text":"low-level languages cannot be understood by computers. "}],
   "cspcode":"2.2.3C",
   "description":"High vs Low language",
   "question":"The main difference between <i>low-level</i> and <i>high-level</i> programming languages is ______. ",
   "source":"mcsp-4",
   "type":"Mc",
   "wrongfeedback":"",
   "hint":"We code in high level programming languages that are then translated to lower level languages like machine code.",
   "heading":"Abstraction"},  
  { 
      "choices":[
          {"feedback":"A is not correct. When you arrange a deck of cards you are <i>sorting</i>, not searching.",
           "score":"-1",
           "text":"A. Arranging a deck of cards from the lowest to the highest value cards. "},
    {"feedback":"B is correct. Looking up a phone number is a problem that can be solved by a sequential search, although binary search would be faster since the phone book is alphabetized.",
     "score":"0.5",
     "text":"B. Looking up a phone number in the phone book given the person's full (unique) name."},
    {"feedback":"C is not correct. Searching algorithms are used to find an element in a list, not to average a list of numbers.",
     "score":"-1",
     "text":"C. Averaging a list of numbers."},
    {"feedback":"D is correct! Looking up a person's name given a phone number could be solved by a linear search. You would need to start at one end of the phone book and check each phone number individually, in order, until you find the phone number you were given and then you can find the last name associated with the phone number.",
     "score":"0.5",
     "text":"D. Looking up a person's name in the phone book given the person's phone number. "}],
    "cspcode":"4.2.4H",
   "description":"Sequential Search",
   "question":"Which of the problems below could be solved with a <b><i>linear (sequential) search</i></b> algorithm?",
   "source":"mcsp-5",
   "type":"Ma",
   "wrongfeedback":"",
   "hint":"A linear or sequential search is used to find an element in a list searching from the first element to the last.",
   "heading":"Linear Search" 
  },
  { 'choices': [ { 'feedback': 'No, <i>A memory chip</i> is a piece of hardware that contains electronic circuits that store information.',
                   'score': 0.0,
                   'text': 'Memory chip'},
                 { 'feedback': "That's correct.  An operating system is an example of software, not hardware.",
                   'score': 1.0,
                   'text': 'WIndows Operating System'},
                 { 'feedback': "No, A computer's <i>motherboard </i>is a device that contains all of the computer's main hardware components, such as its main memory (RAM) and its central processing unit (CPU).",
                   'score': 0.0,
                   'text': 'Motherboard'},
                 { 'feedback': 'No, An <i>integrated circuit </i>is a hardware device that contains many millions of electronic elements such as transistors and gates. ICs are used for storing and processing information.&nbsp;',
                   'score': 0.0,
                   'text': 'Integrated circuit'}],
    'cspcode': '2.2.3',
    'description': 'Not an example of hardware',
    
    'question': 'Which of the following is <u>not</u> an example of <i>hardware</i>? ',
    'source': 'mcsp-2',
    'type': "Mc",
    'heading': "Hardware/Software",
    'hint': "",
     'wrongfeedback': ''},
  { 'choices': [ { 'feedback': 'A is right.  Hypertext documents are those that follow the HypterText Transfer Protocol (HTTP).',
                   'score': 0.5,
                   'text': 'A. is a system of interlinked hypertext documents '},
                 { 'feedback': 'B is right. The HyperText Transfer Protocol (HTTP) controls the WWW. It was first proposed by Tim Berners-Lee.',
                   'score': 0.5,
                   'text': 'B. uses the HTTP protocol '},
                 { 'feedback': 'C is not correct. The WWW is not maintained by any one company.  Its content is contributed by its billions ofusers throughout the world.',
                   'score': -1.0,
                   'text': 'C. is maintained by Google and Facebook '},
                 { 'feedback': 'Sorry, D is not correct. The WWW was first proposed by Tim Berners-Lee.',
                   'score': -1.0,
                   'text': 'D. was invented by Al Gore.'}],
    'cspcode': '6.1.1',
    'description': 'Definition of The WWW',
    'heading': 'WWW',
    'hint': '',
    'question': 'The World Wide Web (WWW) _______________.   <br>Choose all that apply. ',
    'source': 'mcsp-7',
    'type': "Ma",
    'wrongfeedback': ''},
  { 'choices': [ { 'feedback': 'Sorry, 10 is a number.  It is a value not a variable.',
                   'score': -1.0,
                   'text': '10'},
                 { 'feedback': "Yes, <i>paintBrush</i>&nbsp;is an abstract symbol for some particular value -- although we don't know what value it is referring to here.",
                   'score': 0.5,
                   'text': 'paintBrush'},
                 { 'feedback': 'Sorry, "hello" is a text value.  It is not a variable.  Text values are always represented in quote marks.',
                   'score': -1.0,
                   'text': '"hello"'},
                 { 'feedback': "Yes. <i>x</i>&nbsp;is an abstract symbol that could be used for a variable name. &nbsp;We don't know what value it is referring to here.&nbsp;",
                   'score': 0.5,
                   'text': 'x'}],
    'cspcode': '5.2.1C',
    'description': 'Variables are abstract symbols',
     'heading': 'Variables',
    'hint': '',
    'question': 'A <i style="font-weight: bold;">variable</i>&nbsp;is an abstract symbol that refers to some particular value. &nbsp;Which of the following symbols is a variable?',
    'source': 'mcsp-3',
    'type': "Ma",
    'wrongfeedback': ''},
  { 
    'description': 'Index of No Way',
    'feedback': 'That\'s right! The text "No way" occurs as the third item in the list, so its index is 3.',
                   'matcher': 'numeric',
                   'response': '3',
                   'score': '1.0',
    'hint': 'Starting with the first item, count how many items down the list "No way" is.',
   "cspcode":"5.3.1K",
   "source":"mcsp-3",
   "heading":"Lists",
    'question': 'Lists are <i>indexed</i>, or numbered, starting with 1, which means that you can retrieve any item from a list by giving its index. For the list below, what is the index of "No way"? Type your answer into the text box. <br>   <apml>list <- [\"Yes\", \"No\", \"No Way\", \"Maybe\", \"Unsure\"]</apml>',
    'type': "Fi",
    'wrongfeedback': 'No, the text "No way" occurs as the third item in the list, so its index is 3.'},  
  { 'choices': [ { 'feedback': " The DNS is a lookup service.  It doesn't create IP addresses.",
                   'score': 0.0,
                   'text': 'creates IP addresses for clients and servers '},
                 { 'feedback': ' The DNS is a service that pairs domain names (www.trincoll.edu) with IP addresses (157.252.176.180).',
                   'score': 0.0,
                   'text': 'divides the Internet up into distinct and separate networks '},
                 { 'feedback': ' The DNS is a de-centralized system.  DNS servers are distributed around the Internet and they work together to resolve domain names (www.trincoll.edu) into IP addresses (157.252.176.180).',
                   'score': 0.0,
                   'text': "is managed by a centralized server that knows all of the Internet's domain names "},
                 { 'feedback': "That's right! When we type www.google.com into the address bar, the DNS translates www.google.com into Google's IP address (64.233.160.0) for us. It's much easier for us to remember www.google.com than for us to remember Google's IP address (64.233.160.0)!",
                   'score': 1.0,
                   'text': 'translates easy-to-remember domain names into IP addresses '}],
    'cspcode': '6.1.1G',
    'description': 'DNS Definition',
    'hint': '',
    'heading': 'DNS',
    'question': 'The Domain Name System __________________. ',
    'source': 'mcsp-7',
    'type': "Mc",
    'wrongfeedback': ''},
  { 'choices': [ { 'feedback': 'Sorry, abstract does not mean more complex.',
                   'score': -1.0,
                   'text': 'Complexing'},
                 { 'feedback': 'Sorry, abstract does not mean more complicated.',
                   'score': -1.0,
                   'text': 'Complicating'},
                 { 'feedback': 'Condensing is correct! Condensing is another way to describe abstraction.', 'score': 0.5, 'text': 'Condensing'},
                 { 'feedback': 'Simplifying is correct! Simplifying is another way to describe abstraction.', 'score': 0.5, 'text': 'Simplifying'}],
    'cspcode': '2.2.1',
    'description': 'Abstraction in CS',
    'hint': 'Abstraction refers to representing objects at a higher-level without all the specific details found at a lower level representation.',
    'heading': 'Abstraction',
    'question': 'In Computer Science, the process of abstracting also means:',
    'source': 'mcsp-2',
    'type': "Ma",
    'wrongfeedback': ''},
  { 'choices': [ { 'feedback': "No, the programmer's knowledge can be used to determine if statements are formulated correctly, this is not what is meant by syntax.",
                   'score': 0.0,
                   'text': "programmer's knowledge "},
                 { 'feedback': 'No, the compiler runs the program statements whether or not they are formulated correctly. If there is a syntax error, the compiler will inform you that there is an error.',
                   'score': 0.0,
                   'text': 'compiler '},
                 { 'feedback': "No, the programming language is the language the statements are written in. The programming language itself does not determine if the statements are formulated correctly. The programming language's syntax does this.",
                   'score': 0.0,
                   'text': 'programming language '},
                 { 'feedback': "That's right! Programming languages all have syntax, a set of rules, that must be followed when writing code.",
                   'score': 1.0,
                   'text': 'set of rules'}],
    'cspcode': '5.1.2',
    'description': 'Definition of Syntax',
    'hint': '',
    'heading': 'Syntax',
    'question': 'In computer programming, <b><i>syntax</i></b> is the __________ that determines whether statements are correctly formulated. ',
    'source': 'mcsp-5',
    'type': "Mc",
    'wrongfeedback': ''},
  { 'choices': [ 
                 { 'feedback': 'Yes.  In the worst case, when N is prime,  the loop goes through N/2 calculations, each one testing whether N is divisible by K (i.e., whether N/K leaves a remainder of 0).  So this runs in linear time, proportional to the size of N.',
                   'score': 1.0,
                   'text': 'Runs in a reasonable time.'},
                
                 { 'feedback': 'Try again. Algorithms that contain loops that run approximately N times (the size of the input) run in a reasonable polynomial time.',
                   'score': 0.0,
                   'text': 'Does not run in a reasonable time.'}],
    'cspcode': '4.2.1',
    'description': '5 Analysis Is a Prime',
    'question': 'How would you classify this algorithm that determines whether N is a prime number?<pre>For each number K from 2 to N/2 <br>   if N is divisible by K <br>        Output False <br>Output True</pre>',
 'hint': 'Algorithms that contain loops that run approximately N times (the size of the input) run in a reasonable (polynomial with respect to N) time. Exponential time such as 2<sup>N</sup> would not be a reasonable time.',
    'heading': 'Algorithms',
   'source': 'mcsp-5',
    'type': "Mc"},
  { 'choices': [ { 'feedback': "No, the definition contains details about chairs, so is not as abstract as the word 'chair' itself.",
                   'score': 0.0,
                   'text': "The dictionary definition of the word 'chair'."},
                 { 'feedback': "That's correct.  Good.",
                   'score': 1.0,
                   'text': "The word 'chair' itself."},
                 { 'feedback': "No, the picture contains details about a chair, so it is not as abstract as the word 'chair' itself.",
                   'score': 0.0,
                   'text': 'A picture of a chair.'},
                 { 'feedback': "No, the physical chair itself is very detailed and concrete.  It's the very opposite of abstract.",
                   'score': 0.0,
                   'text': 'The chair itself.'}],
    'cspcode': '2.2.1',
    'description': 'Most abstract - chair',
    'hint': 'Abstraction refers to representing objects at a higher-level without all the specific details found at a lower level representation.',  
   'heading': 'Abstraction',
    'question': 'In general, which of the following is the most abstract when it comes to talking about chairs?',
    'source': 'mcsp-2',
    'type': "Mc",
    'wrongfeedback': ''},
  { 
    'description': 'Caesar cipher decryption',
     'feedback': "That's right! <em>ecguct</em> is <em>caesar</em> after being encrypted with a Caesar cipher of shift 2 because each letter is shifted 2 letters down in the alphabet.",
                   'matcher': 'case_insensitive',
                   'response': 'caesar',
                   'score': '1.0',
    'hint': 'This Caesar cipher shifts to the left',
    'question': 'The following word was encrypted using a Caesar cipher with a shift of 2: <b>ecguct</b>. What word is it? Type your answer into the text box. ',
    "hint": "In Caesar cipher decryption with shift 2, each letter is replaced with a letter 2 letters up in the alphabet, so c becomes a.",
        "heading": "Cryptography",
        "cspcode":"6.3.1K",
        "source":"mcsp-7",
    'type': "Fi",
    'wrongfeedback': 'Try again. You should get a word in English that is on this page. In Caesar cipher decryption with shift 2, each letter is replaced with a letter 2 letters up in the alphabet, so c becomes a.'},
  { 'choices': [ { 'feedback': 'Yes. Because the symbol contains fewer details than the truth table it is <i><b>more abstract</b></i>.',
                   'score': 1.0,
                   'text': 'True'},
                 { 'feedback': 'Sorry, the symbol contains fewer details than the truth table so it is <i><b>more abstract</b></i>.',
                   'score': 0.0,
                   'text': 'False'}],
    'description': 'T/F AND symbol more abstract',
    'question': 'True or False.  The symbol for an AND gate is more abstract than the <i>truth table</i> that defines its behavior. ',
     'cspcode': '2.2.1',
    'hint': 'Abstraction refers to representing objects at a higher-level without all the specific details found in a lower level representation.',  
   'heading': 'Abstraction',
    'source': 'mcsp-2', 
    'type': "Mc",
    'wrongfeedback': ''},
  { 'choices': [ { 'feedback': "A is right! E-mail, SMS, Facebook, and Twitter have all given us new ways to communicate with one another.",
                   'score': 0.5,
                   'text': 'A. fostering new ways for individuals to communicate'},
                 { 'feedback': "B is not right. E-mail, SMS, Facebook, and Twitter have all raised concerns about our privacy and security. ",
                   'score': -1.0,
                   'text': 'B. providing always secure and private communication.'},
                 { 'feedback': 'C is not right. Social media probably has not improved our reading and writing skills.',
                   'score': -1.0,
                   'text': 'C. improving our reading and writing skills '},
                 { 'feedback': "D is right! E-mail, SMS, Facebook, and Twitter all allow us to spread information quickly and widely. ",
                   'score': 0.5,
                   'text': 'D. allowing individuals to spread information quickly and widely '}],
    'cspcode': '7.1.1A',
    'description': 'Societal Impacts',
     'hint': '',
    'heading': 'Global Impact',
    'question': 'E-mail, SMS, and social media, such as Facebook and Twitter, have impacted our society by _______________. <br><b>Choose all that apply. </b>',
    'source': 'mcsp-7',
    'type': "Ma",
    'wrongfeedback': ''}];