var quiz_data = [ { 'choices': [ { u'feedback': u'This is challenging, but rewarding!',
                   u'score': 0.0,
                   u'text': u'a person who makes up secret codes'},
                 { u'feedback': u"That's right! A cipher, such as the Caesar cipher, is an algorithm that is used to encrypt or scramble text so that it is unreadable unless one knows how to descrypt it. A cipher converts plaintext into ciphertext and vice versa.",
                   u'score': 1.0,
                   u'text': u'an algorithm that is used to scramble text so that it can be passed in secret'},
                 { u'feedback': u'This is challenging, but rewarding!',
                   u'score': 0.0,
                   u'text': u'a lock that can be used to lock a message in a lock box'},
                 { u'feedback': u'This is challenging, but rewarding!',
                   u'score': 0.0,
                   u'text': u'any puzzle, such as a crossword or Sudoku puzzle'}],
    'cspcode': '0.0.0X',
    'description': u'Cipher definition',
    'permute': False,
    'question': u'A cipher is _________________________.',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'Of course it\u2019s tough \u2013 school is here to makes our brains stronger!',
                   u'score': 0.0,
                   u'text': u'True'},
                 { u'feedback': u'', u'score': 1.0, u'text': u'False'}],
    'cspcode': '0.0.0X',
    'description': u'Memory vs Storage in data processing',
    'permute': False,
    'question': u'Processing data requires the same amount of bytes in memory as it does bytes to store the data.',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 0.33,
                   u'text': u'a. Cloud computing relieves users from having to backup their own data and information. '},
                 { u'feedback': u'',
                   u'score': 0.33,
                   u'text': u'b. Cloud computing makes it easier to share information.'},
                 { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': -1.0,
                   u'text': u"c. Information is stored on each user's computer. "},
                 { u'feedback': u'',
                   u'score': 0.34,
                   u'text': u'd. Users can access information that is on the cloud from anywhere that has an Internet connection. '}],
    'cspcode': '0.0.0X',
    'description': u'Cloud Computing Advantages',
    'permute': False,
    'question': u'Which of the following are advantages of cloud computing? \n<br>\n<b>Choose all that apply.</b>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': 0.0,
                   u'text': u'a. Sequence '},
                 { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': 0.0,
                   u'text': u'b. Selection '},
                 { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': 0.0,
                   u'text': u'c. Repeat '},
                 { u'feedback': u"That's right! A For Each loop is used for iteration which is also referred to as repetition. ",
                   u'score': 1.0,
                   u'text': u'd. Repetition '}],
    'cspcode': '0.0.0X',
    'description': u'For Each is Repetition',
    'permute': False,
    'question': u'What type of control structure is a For Each loop? ',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(A)The number 0 is displayed.\n\n\n'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(B) The number 6 is displayed.'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(C) The number 10 is displayed.'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'(D) Nothing is displayed; the program results in an infinite loop.'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P Exam Prep Calculate Sum',
    'permute': False,
    'question': u'Consider the following program code.\n\n<br><br><div style="text-align: center;"><img src="https://ram8647.appspot.com/mobileCSP/assets/img/Q20Code.PNG" class="yui-img" title="" alt="" style="line-height: 1.22;"><br><br></div>Which of the following best describes the result of running the program code?<br><br>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'True'},
                 { u'feedback': u"That's right! Data packets sent over the Internet have different possible routes that they can take to get to their destination.",
                   u'score': 1.0,
                   u'text': u'False'}],
    'cspcode': '0.0.0X',
    'description': u'Packet switching - dedicated route',
    'permute': False,
    'question': u'True or False: For every packet of data sent over the Internet, there is only one route it can take to reach its destination. ',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Well described key impacts'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Adequately described some impacts'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Poorly described'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'Missing'}],
    'cspcode': '0.0.0X',
    'description': u'EPT - Short Term Impacts',
    'question': u'Short-term Impacts - Report describes the short term impacts of the innovation',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Authors work efficiently and coordinate well'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Authors work together with some problems'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Authors fail to work together'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Did not complete project with a partner'}],
    'cspcode': '0.0.0X',
    'description': u'CP1 - Collaboration',
    'question': u'Collaboration',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': 0.0,
                   u'text': u'a. Off '},
                 { u'feedback': u"That's right! Setting the Texting component's Receiving Enabled property to Foreground makes it so that the app only receives texts while the app is open on the device. ",
                   u'score': 1.0,
                   u'text': u'b. Foreground '},
                 { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': 0.0,
                   u'text': u'c. On '},
                 { u'feedback': u'Try asking a classmate for advice\u2014s/he may be able to explain/suggest some ideas or recommend some strategies.',
                   u'score': 0.0,
                   u'text': u'd. Always '}],
    'cspcode': '0.0.0X',
    'description': u'Receiving texts',
    'permute': False,
    'question': u"If a user wants an app to receive texts only when the app is open, he/she should set the Texting component's Receiving Enabled property to: ",
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'This is correct',
                   u'score': 1.0,
                   u'text': u'I and II only'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'I and III only'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'II and III only'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'I, II, and III'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P EXAM PREP Digital Audio Files',
    'permute': False,
    'question': u'Which of the following are true statements about digital audio files?\n\n<br><br>I. An audio file can be created by using samples of one or more existing audio files.\n\n<br>II. An audio file can be created by using a computer program to synthesize a new sound.\n\n<br>III. An audio file that has gone through lossy compression can be restored to its original uncompressed version.\n\n<br>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'cspcode': '0.0.0X',
    'description': u'Assembly Language Avg Program',
    'graders': [ { u'feedback': u"<p>The average of 5 plus 8 for our 4-bit simulator is 6.\n</p>\n<p>\n  You might have expected the result to be 6.5, which is the average of 5 + 8.  \n  But our 4-bit computer can only represent the positive whole numbers, \n  from 0 to 255. We have not given it an abstraction for representing \n  so-called <b>real numbers</b> -- i.e., numbers with a decimal point.\n</p>\n<p>\n  Although it's beyond the scope of this course, computers use a representation\n  scheme know as <i>Twos complement</i> to represent both positive and negative\n  real numbers.\n</p>",
                   u'matcher': u'case_insensitive',
                   u'response': u'6',
                   u'score': u'1.0'}],
    'hint': u'It might help to work in pairs or teams on this problem. ',
    'question': u'<h3>What\'s the Average</h3>\n<p>\n  <a target="_blank" href="http://appinventor.cs.trincoll.edu/csp/webapps/computer/gen2.html">Using Generation 2</a>\n  of the 4-bit computer write an <b>assembly language program</b> that \n  will calculate the average of the binary numbers 00000101 and 00001000 and output \n  the result. Then load the program into RAM and run it.\n</p>\n<p>\n  What value does the program output? \n</p>\n<p>\n  Are you surprised at the result?\n</p>\n\n',
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u'You can do it.  Keep trying. '},
  { 'choices': [ { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'If the user has already answered the current question correctly -- i.e., if <tt>correctAnswers</tt> is true -- 1 is added to the number of correct answers displayed.'},
                 { u'feedback': u'Let me add new information to help you solve this; the quiz app does increment the index to move to the next question, but not in these blocks.',
                   u'score': 0.0,
                   u'text': u'The blocks increment the index to move on to the next question.'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'The blocks check the "indexth" item of the correctAnswers list. If it is not true, it sets it to true.'},
                 { u'feedback': u"Let me add new information to help you solve this; correctAnswers starts as a list of three false values, because the user hasn't answered anything correctly when the app (quiz) begins. One of the answerChoices is changed only when a right answer is chosen ",
                   u'score': 0.0,
                   u'text': u'The blocks iterate through the correctAnswers list and set them all to true.'}],
    'cspcode': '0.0.0X',
    'description': u'AnswerChoices list remembers correct answers',
    'permute': False,
    'question': u'Consider the following blocks, which are part of a solution for the extended quiz app for this unit.<br><img src="http://appinventor.org/assets/img/countCorrect.png" class="yui-img"><br>The blocks do which of the following:',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(A) Is anyone there?'},
                 { u'feedback': u"That's correct!",
                   u'score': 1.0,
                   u'text': u'(B) Better late than never.'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(C) Hello. Is anyone there?'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(D) Hello. Better late than never.'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P Exam Prep 13 If Else',
    'permute': False,
    'question': u'Consider the code segment below.<br><img src="https://ram8647.appspot.com/mobileCSP/assets/img/APExamPrepQ13.PNG" class="yui-img selected" title="" alt="" style="width: 300px;"><br>\nIf the variables <i>onTime</i> and <i>absent</i> both have the value <i>false</i>, what is displayed as a result of running the code segment?',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u"True. If/else blocks are control blocks that are used to control an app's behavior. They do this by checking to see if a certain condition is True or False. \n",
                   u'score': 0.33,
                   u'text': u"To control the app's behavior. "},
                 { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': -1.0,
                   u'text': u'To repeat a sequence of statements. '},
                 { u'feedback': u'True. In the Pong game, you used the If/else block to determine if the the ball had reached the bottom edge of the screen. That is, to determine whether the condition was True or False. If this were true and the ball did in fact reached the bottom edge of the screen, then the game ended. Else, the ball has reached a different edge on the screen and bounced off that edge. ',
                   u'score': 0.33,
                   u'text': u'To check if a certain condition is True or False. '},
                 { u'feedback': u'True. Depending on whether the condition in the If statement is True or False, the If/else block tells the app which path to take in the code. ',
                   u'score': 0.34,
                   u'text': u'To tell the app which path to take in the code. '}],
    'cspcode': '0.0.0X',
    'description': u'Purpose of If/Else Blocks',
    'permute': False,
    'question': u'What are <b><i>If/else blocks</i></b> used for when programming an app? \n<br>\nChoose all that apply. ',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'', u'score': 1.0, u'text': u'True'},
                 { u'feedback': u'Of course it\u2019s tough \u2013 school is here to makes our brains stronger!',
                   u'score': 0.0,
                   u'text': u'False'}],
    'cspcode': '0.0.0X',
    'description': u'Abstraction Examples in CS',
    'permute': False,
    'question': u'True or False: Two examples of abstraction in Computer Science are Data Abstraction and Procedural Abstraction. \n',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'1, 1, 1<br>0, 3<br>0, 3<br>1, 1, 1<br>1, 1, 1<br>1, 1, 1<br>1, 1, 1<br>1, 1, 1<br>1, 1, 1<br>'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'1, 3, 1<br>0, 1, 3, 1<br>0, 1, 4<br>0, 1, 4<br>0, 1, 3, 1<br>1, 3, 1'},
                 { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'1, 3<br>0, 1, 3<br>0, 2, 2<br>2, 2<br>3, 1<br>0, 3, 1'}],
    'cspcode': '0.0.0X',
    'description': u'RLE - Letter to numbers',
    'permute': False,
    'question': u'Which set of numbers would encode the letter "c"?',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'', u'score': 0.0, u'text': u'(A) A'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'(B) L'},
                 { u'feedback': u'This is correct',
                   u'score': 1.0,
                   u'text': u'(C) V'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'(D) Y'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P EXAM PREP Music Database',
    'permute': False,
    'question': u'<br>.&nbsp;<img src="https://ram8647.appspot.com/mobileCSP/assets/img/SampleExamQuestion5ASCII.PNG" class="yui-img">',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'cspcode': '0.0.0X',
    'description': u'5.SortRadix.1',
    'graders': [ { u'feedback': u"The card sorting example is using <b>base-4</b>.  Here's what the notation looks like:\n<table>\n<tr><th>Card</th><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td>\n<td>9</td><td>10</td><td>Jack</td><td>Queen</td><td>King</td><td>Ace</td></tr>\n<tr><th>Base-4</th><td>02</td><td>03</td><td>10</td><td>11</td><td>12</td><td>13</td><td>20</td>\n<td>21</td><td>22</td><td>23</td><td>30</td><td>31</td><td>32</td></tr>\n</table>\n\n<p>Given this notation, if you sort by <i>least significant digit</i> first, then the 2, 6, 10 and  Ace would go in bucket 0, on the first pass, as seen in the video.\n\n<p>Can you see how the other cards are placed into buckets?",
                   u'matcher': u'case_insensitive',
                   u'response': u'4',
                   u'score': u'1.0'}],
    'hint': u'Think about the example of sorting the base-10 numbers.  How many buckets were required in that example.',
    'question': u'What <i>base</i> (<i>radix</i>) is being used in the video demonstration of sorting\ncards using Radix sort?',
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u"The card sorting example is using <b>base-4</b>.  Here's what the notation looks like:\n<table>\n<tr><th>Card</th><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td>\n<td>9</td><td>10</td><td>Jack</td><td>Queen</td><td>King</td><td>Ace</td></tr>\n<tr><th>Base-4</th><td>02</td><td>03</td><td>10</td><td>11</td><td>12</td><td>13</td><td>20</td>\n<td>21</td><td>22</td><td>23</td><td>30</td><td>31</td><td>32</td></tr>\n</table>\n\n<p>Given this notation, if you sort by <i>least significant digit</i> first, then the 2, 6, 10 and  Ace would go in bucket 0, on the first pass, as seen in the video.\n\n<p>Can you see how the other cards are placed into buckets?\n\n\n\n"},
  { 'choices': [ { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn. Try reviewing this; some Big Data sets do contain very large number, such as 1,980,000,000.3021342, but <i>all</i> Big Data sets do not contain very large numbers.',
                   u'score': 0.0,
                   u'text': u'data sets that contain very large numbers '},
                 { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn. Try reviewing this; you may find that some Big Data sets are owned by big corporations such as banks or oil companies, but you can also find Big Data sets that are owned by small corporations or even individuals.',
                   u'score': 0.0,
                   u'text': u'data sets that are owned by a big corporation '},
                 { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn. Try reviewing this; not all Big Data is stored in the cloud. Some companies save their Big Data in Excel spreadsheets on a hard drive in other databases.',
                   u'score': 0.0,
                   u'text': u'data sets that are stored in the cloud '},
                 { u'feedback': u"That's right! Big data sets are extremely large sets of data that are very complex.",
                   u'score': 1.0,
                   u'text': u'data sets that are too large and complex to download and process on a single computer'}],
    'cspcode': '0.0.0X',
    'description': u'Big Data Definition',
    'permute': False,
    'question': u'The term <b><i>Big Data</i></b> refers to _________________.',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'cspcode': '0.0.0X',
    'description': u'TinyDB Two Store Values',
    'graders': [ { u'feedback': u'Good. That\'s right! The second StoreValue block stores the name "Bill" under the tag "Name", with an uppercase \'N\'. Because tags are <b>case sensitive</b>, there are now two values stored in the database, "Mary" is associated with the tag "name" and "Bill" is associated with the tag "Name".   So GetValue will retrieve "Mary" from the TinyDb and assign it to global variable <i>userName</i>.',
                   u'matcher': u'case_insensitive',
                   u'response': u'Mary',
                   u'score': u'1.0'}],
    'hint': u'',
    'question': u'What value would the global variable <i>userName</i> have after the blocks shown here are executed? <br>Type your answer into the textbox. Spelling counts. <br><img src="https://ram8647.appspot.com/mobileCSP/assets/img/TinyDbSetUsernameMary.png" width="350px" class="yui-img"><br>',
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u'TinyDb tags are <i>case sensitive</i>, so the tags "name" and "Name" are two different tags associated with two different values. '},
  { 'choices': [ { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn.',
                   u'score': 0.0,
                   u'text': u'a. Because that would be a bad score. '},
                 { u'feedback': u'Good. If TinyDb does not find anything in the Db under the tag "highest" it will return the empty string. This is how you check that TinyDb does contain a value for a given tag. ',
                   u'score': 1.0,
                   u'text': u'b. Because that would be the value returned by TinyDb if nothing had yet been stored under the tag "highest". '},
                 { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn.',
                   u'score': 0.0,
                   u'text': u'c. Because TinyDb can only be used to store numbers, not strings. '},
                 { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn.',
                   u'score': 0.0,
                   u'text': u'd. Because TinyDb returns an empty string whenever the network is not available. '}],
    'cspcode': '0.0.0X',
    'description': u'TinyDB Test Empty String',
    'permute': False,
    'question': u'In the block shown here why is it necessary to test whether the highestScore equals the empty string? <br><img src="https://ram8647.appspot.com/mobileCSP/assets/img/getHighestScore.png" class="yui-img"><br>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u"Yes, to think of a simple example, if you were using 4 bits to represent numbers you wouldn't be able to represent the number 17, so you wouldn't be able to add 17 + 8.   Modern computers use 32 or 64 bits to represent whole numbers, which are called <i>integers</i>.  With 32 bits, you can represent 2<sup>32</sup> different values. That's 4,294,967,296, more than 4 billion values.  But, of course, there are still numbers that would cause overflow errors -- e.g., 4,300,000,000 could not be represented using 32 bits.  This potential for overflow error is a necessary implication of using a <i><b>finite</b></i> representation to model the <i><b>infinite</b></i> concept of number. ",
                   u'score': 1.0,
                   u'text': u'True.'},
                 { u'feedback': u"This is challenging, but rewarding! Using a fixed number of bits to represent numbers does limit the range of problems you can solve.  For example, if you were using 4 bits to represent numbers you wouldn't be able to represent the number 17, so you wouldn't be able to add 17 + 8.  Modern computers use 32 or 64 bits to represent whole numbers, which are called <i>integers</i>.  With 32 bits, you can represent 2<sup>32</sup> different values. That's 4,294,967,296, more than 4 billion values.  But, of course, there are still numbers that would cause overflow errors -- e.g., 4,300,000,000 could not be represented using 32 bits.  This potential for overflow error is a necessary implication of using a <i><b>finite</b></i> representation to model the <i><b>infinite</b></i> concept of number. ",
                   u'score': 0.0,
                   u'text': u'False'}],
    'cspcode': '0.0.0X',
    'description': u'Binary numbers fixed number of bits',
    'permute': False,
    'question': u'True or False. Using a fixed number of bits to represent numbers limits the range of values and hence limits the range of problems that can be solved with that representation. ',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'This is challenging, but rewarding! The <i>Halting Problem</i> is an example of an unsolvable problem. ',
                   u'score': 0.0,
                   u'text': u'True'},
                 { u'feedback': u'Yes. The <i>Halting Problem</i> is an example of an undecidable problem, as Turing proved.',
                   u'score': 1.0,
                   u'text': u'False'}],
    'cspcode': '0.0.0X',
    'description': u'T/F All problems solvable',
    'permute': False,
    'question': u'True or False:  An algorithm can be found for any computational problem whatsoever.',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'a. Send a different text message to each of the five members. '},
                 { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'b. Send the same text message to one member five different times.'},
                 { u'feedback': u"That's right! For Each loops perform iteration, that is it repeats the same thing over for each item in a list. In this case, the For Each loop would send the same text message to each of the five members.",
                   u'score': 1.0,
                   u'text': u'c. Send the same text message to each of the five members. '},
                 { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'd. Send five different text messages to one member. '}],
    'cspcode': '0.0.0X',
    'description': u'For Each Loop to Send Text',
    'permute': False,
    'question': u'If there are five members in the broadcast hub, what would the following block of code do? <br><br><img class="yui-img" src="https://ram8647.appspot.com/mobileCSP/assets/img/ForEach.PNG"><br>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'', u'score': 1.0, u'text': u'(A) I'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'(B) II'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'(C) I and II'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(D) Neither I nor II'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P Exam Prep Digital Certificates',
    'permute': False,
    'question': u'Which of the following are true statements about digital certificates in Web browsers?<div><br></div><div><span class="Apple-tab-span" style="white-space:pre">\t</span>I. Digital certificates are used to verify the ownership of encrypted keys used in secured&nbsp;<span style="line-height: 14.4182px;">communication.</span><span style="line-height: 1.22;">&nbsp;</span></div><div><br></div><div><span class="Apple-tab-span" style="white-space:pre">\t</span>II. Digital certificates are used to verify that the connection to a Web site is fault tolerant<span style="line-height: 1.22;">.<br><br></span></div>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'cspcode': '0.0.0X',
    'description': u'Evaluate modulo expression',
    'graders': [ { u'feedback': u'3<sup>3</sup> mod 5 = 27 mod 5 = 2',
                   u'matcher': u'case_insensitive',
                   u'response': u'2',
                   u'score': u'1.0'}],
    'hint': u'First raise 3 to the 3rd power then divide by 5 and take the remainder.',
    'question': u'Evaluate the following expression.  Type your answer into the Textbox.\n<br>\n<br>\n3<sup>3</sup> mod 5',
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'', u'score': 0.5, u'text': u'(A) Author'},
                 { u'feedback': u'', u'score': 0.5, u'text': u'(B) Title'},
                 { u'feedback': u'', u'score': -1.0, u'text': u'(C) Genre'},
                 { u'feedback': u'',
                   u'score': -1.0,
                   u'text': u'(D) Quantity Available'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P Exam Prep Bookstore Database',
    'permute': False,
    'question': u'A bookstore has a database containing information about each book for sale in the store. A sample portion of the database is shown below.\n\n<br><br><div style="text-align: center;"><img src="https://ram8647.appspot.com/mobileCSP/assets/img/Q28Table.PNG" class="yui-img selected" title="" alt="" style="line-height: 1.22;"><br><br></div>\n\nA store employee wants to calculate the total amount of money the store will receive if they sell\n\nall of the available science fiction books. Which columns in the database can be ignored and \n\nstill allow the employee to perform this calculation?\n<br><br>&nbsp;Select <u>two</u> answers.<br><br>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Works exactly as intended'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Works as intended, but with some small bugs'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u"Doesn't accomplish intended tasks"},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Did not complete'}],
    'cspcode': '0.0.0X',
    'description': u'CP2 - Does it work',
    'question': u'Does the app work?',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'A few minor errors'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Some significant errors'},
                 { u'feedback': u'', u'score': 1.0, u'text': u'Many errors'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Did not complete portfolio write-up'}],
    'cspcode': '0.0.0X',
    'description': u'CP2 - Portfolio grammar',
    'question': u'Portfolio write-up grammar & spelling',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn. Try reviewing this; when the Ball collides with the paddle the game continues and the Ball is sent back up toward the top of the screen.',
                   u'score': 0.0,
                   u'text': u'When the Ball collides with the paddle. '},
                 { u'feedback': u"That's right! In this app the Ball1.EdgeReached event handlerchecks which edge the Ball has reached and decides if the bottom edge is reached, then the game is over.",
                   u'score': 1.0,
                   u'text': u'When the Ball reaches an edge. '},
                 { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn. Try reviewing this; dragging the paddle does not end the game. It is used to save the ball from reaching the bottom edge.',
                   u'score': 0.0,
                   u'text': u'When the paddle is dragged. '},
                 { u'feedback': u'OK, so you didn\u2019t get it right this time. Let\u2019s look at this as an opportunity to learn. Try reviewing this; the Ball bouncing does not end the game. If the ball bounces, that means it has hit a side edge, a top edge, or the paddle and the game continues.',
                   u'score': 0.0,
                   u'text': u'When the Ball bounces. '}],
    'cspcode': '0.0.0X',
    'description': u'EdgeReached Event Ends the Game',
    'permute': False,
    'question': u'What event checks to see if the Ball has made it past the paddle to the bottom of the screen? ',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'Of course it\u2019s tough \u2013 school is here to makes our brains stronger!',
                   u'score': 0.0,
                   u'text': u'a. client'},
                 { u'feedback': u'', u'score': 1.0, u'text': u'b. server'}],
    'cspcode': '0.0.0X',
    'description': u'Server Example',
    'permute': False,
    'question': u"Google's search engine is an example of a __________. ",
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u"This is challenging, but rewarding! Remember that not all sorting algorithms involve comparisons of values.  For example, in bucket sort it is not necessary to compare items to each other in order to sort a list.  A nice analogy for bucket sort is the task of sorting laundry.  When you come to a T-shirt in the unsorted pile, you don't need to compare it to other items in the unsorted pile in order to place it into T-shirt pile. ",
                   u'score': 0.0,
                   u'text': u'how many comparisons are needed to sort the values. '},
                 { u'feedback': u'This is challenging, but rewarding! Not all algorithms involve arranging values in order, for example, the bucket sort does not involve comparing or swapping to put values in order.',
                   u'score': 0.0,
                   u'text': u'whether the algorithm correctly arranges the values in order. '},
                 { u'feedback': u'This is challenging, but rewarding! The efficiency of an algorithm does not focus on whether the algorithm contains a bug.\n',
                   u'score': 0.0,
                   u'text': u'whether or not the algorithm contains a bug. '},
                 { u'feedback': u"That's right! Efficiency in terms of sorting means how long the algorithm takes. Remember that not all sorting algorithms involve comparisons of values. And not all sort algorithms involve swapping values. Although bubble sort involves both comparing and swapping elements, bucket sort is an algorithm that involves neither comparing nor swapping.  A nice analogy for bucket sort is the task of sorting laundry.  When you come to a T-shirt in the unsorted pile, you don't need to compare it to other items in the unsorted pile in order to place it into T-shirt pile. ",
                   u'score': 1.0,
                   u'text': u'how long it takes to arrange the values in order. '},
                 { u'feedback': u'This is challenging, but rewarding! Not all sort algorithms involve swapping values.  For example, bubble sort does involve swapping values but the merge sort that we studied does not involve swapping. ',
                   u'score': 0.0,
                   u'text': u'how many swaps are needed to sort the values. '}],
    'cspcode': '0.0.0X',
    'description': u'Meaning of Sort Efficiency',
    'permute': False,
    'question': u"In talking about sorting algorithms in general, a sort algorithm's <b><i>efficiency </i></b>refers to ______________________. ",
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'The procedure draws a pentagon not a square'},
                 { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u'The procedure draws a triangle not a square'},
                 { u'feedback': u'Even if you call drawSqure(30), a square of size 50 will be drawn. You can replace the 50 with L to get the right behavior.',
                   u'score': 1.0,
                   u'text': u'The procedure always draws a square with sides of size 50. The parameter L is ignored,'},
                 { u'feedback': u'We\u2019re in the learning zone today. Mistakes are our friends!',
                   u'score': 0.0,
                   u'text': u"The procedure parameter isn't specified correctly"}],
    'cspcode': '0.0.0X',
    'description': u'Draw square error',
    'permute': False,
    'question': u'<img src="https://sites.google.com/site/appinventorcourse/ata/drawSquareError.png?attredirects=0" class="yui-img selected"><br>You should be able to draw a square of any size with this procedure by calling it and specifying the parameter L. However, this procedure has a bug. What is the bug?',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Beneficial effects of innovation well thought out and clearly described'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Beneficial effects not well thought out or confusing'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Beneficial effects poorly described'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Missing beneficial effects'}],
    'cspcode': '0.0.0X',
    'description': u'EPT - Beneficial Effects',
    'question': u'Beneficial Effects - The report very well describes the beneficial and harmful effects of the innovation.',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Clearly relates to the effect'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Adequate with some problems'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Not well thought out or confusing'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'Missing'}],
    'cspcode': '0.0.0X',
    'description': u'EPT - Artifact Appropriateness',
    'question': u'Visual Artifact Appropriateness: Paper included a visual artifact that provides additional insight to explain, clarify, or depict the beneficial or harmful effect of the innovation selected.',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'This is challenging, but rewarding! You only find out what the user has chosen in the ListPicker.AfterPicking event.',
                   u'score': 0.0,
                   u'text': u"Determine if the user's choice is correct."},
                 { u'feedback': u'You typically will set the ListPicker.Elements property to the list of items you want to appear',
                   u'score': 1.0,
                   u'text': u'Populate the ListPicker with the choices for the user.'},
                 { u'feedback': u"This is challenging, but rewarding! ListPicker.Selection will be set in ListPicker.AfterPicking to the choice of the user. You typically won't set this property yourself.",
                   u'score': 0.0,
                   u'text': u'Set the Selection property of ListPicker'}],
    'cspcode': '0.0.0X',
    'description': u'ListPicker Before Picking Event',
    'permute': False,
    'question': u'The ListPicker.BeforePicking event is typically used to:',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'If it were easy, you wouldn\u2019t be learning anything! This is not an issue as the quiz will indeed loop back to the first question',
                   u'score': 0.0,
                   u'text': u'The quiz will stop at the last question and not allow the user to return to earlier questions.'},
                 { u'feedback': u'If it were easy, you wouldn\u2019t be learning anything! This is not an issue as the index never gets too big so the select list item always selects a valid item.',
                   u'score': 0.0,
                   u'text': u'The app will stop running and an error message will appear.'},
                 { u'feedback': u'Because of the ">=" in the if-test, the quiz jumps to the first question before the last is displayed. Replacing ">=" with ">" would provide the correct behavior. ',
                   u'score': 1.0,
                   u'text': u'The last question in the quiz will never be reached.'}],
    'cspcode': '0.0.0X',
    'description': u'Index never reaches last problem',
    'permute': False,
    'question': u'The following blocks specify what happens when the user clicks "Next" in a quiz app:<br><img src="https://sites.google.com/site/appinventorcourse/students-spring-2013/quizLoopError.png?attredirects=0&amp;d=1" class="yui-img" width="70%"><br>There is a subtle error in the code such that the quiz won\'t work as desired. What is the problem?',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'This is correct!',
                   u'score': 1.0,
                   u'text': u'(A) Input A must be <i>true</i>.'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(B) Input A must be <i>false</i>.'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(C) Input A can be either <i>true</i> or <i>false</i>.'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'(D) There is no possible value of Input A that will cause the circuit to have the output <i>true</i>.'}],
    'cspcode': '0.0.0X',
    'description': u'AP CS P EXAM PREP Logic Gates',
    'permute': False,
    'question': u'<img src="https://ram8647.appspot.com/mobileCSP/assets/img/SampleExamQuestion6LogicGates.PNG" class="yui-img"><br>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Good, easy to follow'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Could be improved upon'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Seriously flawed'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Did not complete write-up'}],
    'cspcode': '0.0.0X',
    'description': u'CP1 - Portfolio organization',
    'question': u'Portfolio write-up organization',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Well described key long term impacts'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Adequately described some long term impacts'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Poorly described'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'Missing'}],
    'cspcode': '0.0.0X',
    'description': u'EPT - Long Term Impacts',
    'question': u'Long Term Impacts - Report describes the long term impacts of the innovation',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Completely meets specification'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Meets most specification but with some problems'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Fails to meet specifications'},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Did not complete'}],
    'cspcode': '0.0.0X',
    'description': u'CP1 - Specifications',
    'question': u'Specifications (listed under directions)',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u"That's not quite right. Unless the message is very small, it would be divided into multiple packets, each of which is routed individually to the recipient's email.",
                   u'score': 0.0,
                   u'text': u"the Gmail server puts the message into a single packet that is routed through the Internet to the recipient's email \n"},
                 { u'feedback': u"That's right! Information that is sent over the Internet is first divided into packets and then each packet is routed individually over the Internet.",
                   u'score': 1.0,
                   u'text': u"the Gmail server divides the message into packets that are routed individually over the Internet to the recipient's email"},
                 { u'feedback': u"That's not quite right. The packets would be routed independently, possibly using separate paths to the recipient.",
                   u'score': 0.0,
                   u'text': u"the Gmail server divides the message into packets that are routed through a dedicated channel to the recipient's email"},
                 { u'feedback': u"That's not quite right. Unless it is very small, the message would be divided into several packets that are routed independently to the recipient's email.",
                   u'score': 0.0,
                   u'text': u"the Gmail server puts the message into a single packet that is routed through a dedicated channel to the recipient's email"}],
    'cspcode': '0.0.0X',
    'description': u'Packetizing email message',
    'permute': False,
    'question': u'When you send an e-mail message using Gmail in your browser or using the Gmail app __________________. ',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'cspcode': '0.0.0X',
    'description': u'EPT2 - Directions',
    'graders': [ { u'feedback': u'Thank you for submitting! You should now be able to access the peer reviews. (Go back to the main course page and a link to peer reviews will appear below this assessment.)',
                   u'matcher': u'regex',
                   u'response': u'/.*/i',
                   u'score': u'36'}],
    'hint': u'',
    'question': u'\n<h2>The Assignment</h2><p><span class="yui-tag-span yui-tag" tag="span">Review the official proposed<span style="font-size: 13px; line-height: 1.22; color: rgb(68, 68, 68);"> <a href="https://drive.google.com/open?id=0B5ZVxaK8f0u9cXRneVNpcUZoUEU" target="_blank">Explore Performance Task Fall 2015 Version</a> <b style="color: rgb(255, 0, 0); font-size: 13px;">(effective as of 12/01/2015)</b></span><span style="font-size: 13px; line-height: 1.22; color: rgb(68, 68, 68); font-family: arial, sans-serif;">&nbsp;</span>from the College Board. [Note: Looking for the old version?<span style="font-size: 13px; line-height: 1.22; color: rgb(68, 68, 68); font-family: arial, sans-serif;"> </span><a href="https://drive.google.com/folderview?id=0B86iRIPU8oQlfmJrWlNzS2Y1MlRMZ2V1RHAwMXlJUTBBazdnSGFGWDBGTGpBbnNUSVVadEE&amp;usp=sharing" target="_blank" style="font-size: 18px; font-family: yui-tmp;">Try here</a><span style="font-size: 13px; line-height: 1.22; color: rgb(68, 68, 68); font-family: arial, sans-serif;">.] </span>You should select a computing innovation and then carefully follow all of the directions as presented by the College Board. Your written report and artifact should be completed individually and address the requirements and prompts as outlined in the Performance Task directions.\n  \n  <!--Commenting our old requirements that were copied and pasted here.\n  <br></span><b><br>Overview</b></span><br><span class="yui-tag-span yui-tag" tag="span">Computing innovations impact our lives in ways that require considerable study and reflection to fully&nbsp;</span><span style="line-height: 1.22;">understand them. In this Performance Task, you will explore an innovation of your choice. You will then&nbsp;</span><span class="yui-tag-span yui-tag" tag="span">examine the innovation with a critical eye to demonstrate a deep understanding of the innovation, its&nbsp;</span><span style="line-height: 1.22;">development, its functionality, its impact or potential for impact on people and society, and its&nbsp;</span><span style="line-height: 1.22;">relationship to data and the other big ideas studied in this course.</span><br></p><p><b><span class="yui-tag-span yui-tag" tag="span"><span style="color: rgb(68, 68, 68); font-size: 15px; line-height: 1.22;"><br>A. General Requirements</span><span style="color: rgb(68, 68, 68); font-size: 15px; line-height: 1.22;"><br></span></span></b><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Select a computing innovation to investigate that has had a significant impact on society, economy, or&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">culture. You must be able to convey an understanding of the innovation by discussing the relationship of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">the innovation to the principles of computer science, particularly the role data plays and the&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">cybersecurity issues that exist. You will then address specific prompts that call for either a written&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">response or a visual/audio response.&nbsp;<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">For this task, you will include at least three references/citations to sources used to formulate your&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">written responses.&nbsp;<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022 Each source must be a reliable newspaper/magazine article, book, news,&nbsp;or online source that&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">anyone can access.<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022 For each reference, provide the full citation identifying the author, title,&nbsp;source, and, if possible,&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">the date the reference was written or posted. You&nbsp;will <br><span class="Apple-tab-span" style="white-space:pre">\t</span>&nbsp;&nbsp;list these citations at the end of your&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Written Responses submission.<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022 For online references, include the permanent URL and the date on which&nbsp;you accessed the&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">reference.<br></span><span style="line-height: 1.22; font-size: 13px; font-weight: normal;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022&nbsp;At least two of the sources must have been created after the end of the&nbsp;previous academic year.</span></p><ul>\n</ul>\n  \n</span></span></p><p><span class="yui-tag-span yui-tag" tag="span" style="font-size: 15px;"><b>B. Written Requirements</b></span><br><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Submit one PDF document. Your responses to the following prompts must convey a deep level of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">understanding about your chosen innovation and its impact(s). Respond directly to each prompt and&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">clearly label your responses (a, b, c, d, e, f, g, h). Cite information from the reference(s) you used to&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">respond to prompts b, c, d, e, f, g, h.</span><span style="font-size: 13px; line-height: 1.22;"> You have a maximum of 200 words for each response.</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span><b>Purpose<br></b></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>a. Indicate the name of the innovation and provide a clear description of its intended purpose (such&nbsp;</span><span style="line-height: 1.22;">as&nbsp;the problem that the innovation solved, the &nbsp;&nbsp;<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>opportunity that the innovation created, or the&nbsp;</span><span style="line-height: 1.22;">discovery&nbsp;that the innovation made possible).&nbsp;</span></p><p><span style="line-height: 1.22;"><b><span class="Apple-tab-span" style="white-space:pre">\t</span>Effects and Impacts<br></b></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>b. Explain a benefit and/or harmful effect of the innovation.<span class="Apple-tab-span" style="white-space:pre">\t</span><br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>c. Explain an impact the innovation has had, or has the potential to have, on society, economy,&nbsp;</span><span style="line-height: 1.22;">and/or&nbsp;culture.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>d. Indicate one field, other than computer science, which this innovation has impacted or has&nbsp;</span><span style="line-height: 1.22;">the&nbsp;</span><span style="line-height: 1.22;">potential to impact. Describe the impact.</span></p><p><span style="line-height: 1.22;"><b><span class="Apple-tab-span" style="white-space:pre">\t</span>Technical Aspects<br></b></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>When writing your responses, use language that would be understandable to someone who is&nbsp;not&nbsp;</span><span style="line-height: 1.22;">familiar with the innovation.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>e. Describe how a user interacts with the innovation.&nbsp;<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>f. Describe in detail how the innovation\'s technology incorporates at least ONE of the big ideas of&nbsp;</span><span style="line-height: 1.22;">abstraction, algorithms, programming, and/or the&nbsp;<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Internet to accomplish its purpose.</span></p><p><b style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Relationship to Data<br></b><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Discuss the role data plays in your chosen innovation by responding to each of the following:<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>g. Describe how the innovation consumes data (as input), produces data (as output), and/or&nbsp;</span><span style="line-height: 1.22;">transforms data.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>h. Describe at least one data storage concern, privacy concern, or security concern related to the&nbsp;</span><span style="line-height: 1.22;">innovation.</span></p><ul>\n</ul>\n\n<p><span class="yui-tag-span yui-tag" tag="span" style="font-size: 15px;"><b>C. Artifact</b></span><br><span class="yui-tag-span yui-tag" tag="span" style="font-size: 13px; font-weight: normal;">Use computing tools and techniques to create one original visual or audio artifact (a visualization,</span>&nbsp;<span style="font-size: 13px; font-weight: normal; line-height: 1.22;">graphic, video, or audio recording) that elaborates and/or highlights a different and/or deeper aspect of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">the innovation than you provided in your written responses. Submit as a PDF (3 pages maximum), video&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">or audio file (1 minute maximum length and 30 mb maximum size). Acceptable multimedia file types&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">include mp4, wmv, avi, or mov format.</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Your artifact must satisfy ONE of the following requirements:</span></p><p></p><ul><li><span style="line-height: 1.22;">&nbsp; Provide insight into a beneficial and/or harmful effect of the innovation.&nbsp;</span><br></li><li><span style="line-height: 1.22;">&nbsp; Illustrate and/or describe an impact of the innovation on society, economy, and/or culture.</span><br></li></ul><p></p><ul>\n</ul>\n\n<p><span class="yui-tag-span yui-tag" tag="span" style="font-size: 15px;"><b>D. Written Support for Artifact</b></span><br><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Submit one PDF document. Your responses to the following prompts must convey a deep level of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">understanding about your artifact. Clearly label your responses (a, b). <b>You have a maximum of 200&nbsp;</b></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><b>words for each response.</b></span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>a. Explain how your artifact elaborates or highlights a different and/or deeper aspect of the&nbsp;</span><span style="line-height: 1.22;">innovation than you provided in your written responses.<br><span class="Apple-tab-span" style="white-space:pre">\t</span>&nbsp; &nbsp; Demonstrate that your artifact&nbsp;</span><span style="line-height: 1.22;">accomplished ONE of the following requirements:&nbsp;</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t\t</span>\u2022 Provided insight into a beneficial and/or harmful effect of the innovation.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t\t</span>\u2022 Illustrated or describe an impact of the innovation on society, economy, and/or culture.&nbsp;</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>b. Clearly describe the computing tools, techniques, and development process that you used to&nbsp;</span><span style="line-height: 1.22;">create your artifact. Your description must be clear<br><span class="Apple-tab-span" style="white-space:pre">\t</span>&nbsp;&nbsp; &nbsp;enough so that someone can read your&nbsp;</span><span style="line-height: 1.22;">description and reproduce the artifact.</span></p><ul>\n</ul>\n-->\n  \n  \n\n</span></p><h2>Grading Rubric</h2>\nYour project will be graded based on the documents you submit on your portfolio. Your project will be graded using this <a href="https://drive.google.com/open?id=0B86iRIPU8oQlZERvX1g0OTYzc3c" target="_blank" title="">Explore Performance Task Project Rubric DRAFT Pilot June 2016 Version</a> <span class="yui-tag-span yui-tag" tag="span" style="color: rgb(255, 0, 0);"><b>(effective as of 06/24/2016)</b></span>. \n\n<!--[Note: Looking for the old version? <a href="https://drive.google.com/folderview?id=0B86iRIPU8oQlfmJrWlNzS2Y1MlRMZ2V1RHAwMXlJUTBBazdnSGFGWDBGTGpBbnNUSVVadEE&amp;usp=sharing" target="_blank">Try here</a>.]-->\n\n  <!--Commenting out the old table of learning objectives\n<br><br><table width="100%" style="margin:auto;">\n  <tbody><tr>\n    <th style="width:25%">Aspect</th>\n    <th style="width:25%">Learning Objectives</th>\n    <th style="width:50%">Performance Quality</th>\n  </tr>\n\n\n  <tr>\n    <td>Written Responses </td>\n    <td>7.1.1</td>\n    <td>The innovation\u2019s name and intended purpose are described in detail.</td>\n\n  </tr>\n\n\n  <tr>\n    <td></td>\n    <td>7.1.1<br>7.2.1<br>7.3.1<br>7.4.1</td>\n    <td>The response analyzes the innovation\u2019s beneficial and harmful effects and describes, in depth, its overall impact on society and its potential impact in a field other than computer science.</td>\n\n  </tr>\n\n  <tr>\n    <td></td>\n    <td> 1.2.5</td>\n    <td>The response fully explains how a user interacts with the innovation and provides a comprehensive explanation of the relationship of the innovation\u2019s purpose to one or more of the big ideas of the course.</td>\n\n  </tr>\n\n  <tr>\n    <td>Individual Responses on Collaborative Work</td>\n    <td>3.3.1<br>7.3.1<br>7.4.1</td>\n    <td>The response analyzes how the innovation consumes data (as input), produces data (as output), and/or transforms data. The response also explains a concern related to data storage, privacy, or security.</td>\n\n  </tr>\n\n  <tr>\n    <td></td>\n    <td> 1.2.5</td>\n    <td>There is a compelling connection between the program and its stated purpose. and describes the required input and generated output.</td>\n\n</tr>\n\n  <tr>\n    <td>Artifact </td>\n    <td>1.2.1<br>1.2.2<br>1.2.3</td>\n    <td>The artifact extends the information supplied in the written responses. Previously published or   developed work contributes to, or supports, the production of an original artifact, or all of the work in the artifact appears to be original.</td>\n\n  </tr>\n\n    <tr>\n    <td></td>\n    <td>7.1.1<br>7.2.1<br>7.3.1<br>7.4.13</td>\n    <td>The artifact provides deep insight by explaining in explicit detail the beneficial or harmful effects of the innovation or convincingly illustrating its impact on society.</td>\n\n  </tr>\n  \n    <tr>\n    <td>Written Support for Artifact</td>\n    <td>7.1.1<br>7.2.1<br>7.3.1<br>7.4.1</td>\n    <td>The written support provides details that explain and extend the information supplied in the artifact about potential beneficial or harmful effects of the innovation or its impact on society.</td>\n  </tr>\n\n  <tr>\n    <td></td>\n    <td>1.2.2<br>1.2.3<br>1.2.5\n    </td><td>The written support clearly and comprehensively describes the computing tools, techniques, and development process used to create the artifact.</td>\n\n\n  </tr>\n\n\n</tbody></table>\n\n-->\n\n<h2>Submitting</h2>\n<p>Upload your PDF write-up and visual artifact to your portfolio. Submit the URL of your performance task on your portfolio. One pdf, video, or audio per student. (Example: http://www.mysite.com/exploreperformancetaskwriteup.<b>pdf</b>)</p><p></p>',
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u'URL for the Explore Performance Task page of your portfolio:<br>\nExample: http://www.mysite.com/project1writeup.html'},
  { 'choices': [ { u'feedback': u'Don\u2019t worry, it\u2019s hard! Let\u2019s go back and try it again...',
                   u'score': 0.0,
                   u'text': u'transposition cipher'},
                 { u'feedback': u'Don\u2019t worry, it\u2019s hard! Let\u2019s go back and try it again...',
                   u'score': 0.0,
                   u'text': u'bimodal cipher'},
                 { u'feedback': u"That's right! A cipher, such as the Caesar cipher, is an algorithm that is used to encrypt or scramble text so that it is unreadable unless one knows how to descrypt it. A cipher converts plaintext into ciphertext and vice versa.",
                   u'score': 1.0,
                   u'text': u'substitution cipher'},
                 { u'feedback': u'Don\u2019t worry, it\u2019s hard! Let\u2019s go back and try it again...',
                   u'score': 0.0,
                   u'text': u'substantial cipher'}],
    'cspcode': '0.0.0X',
    'description': u'Caesar substitution cipher',
    'permute': False,
    'question': u'A Caesar cipher is an example of a ______________________.',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u"That's right! A broadcast hub is a common or shared connection point between devices on a shared network. A broadcast hub can be used to send messages to the devices on the shared network. ",
                   u'score': 1.0,
                   u'text': u'a. a shared connection point that transmits messages among devices on a network '},
                 { u'feedback': u'If it were easy, you wouldn\u2019t be learning anything!',
                   u'score': 0.0,
                   u'text': u'b. a text message that is broadcasted to lots of people '},
                 { u'feedback': u'If it were easy, you wouldn\u2019t be learning anything!',
                   u'score': 0.0,
                   u'text': u'c. an e-mail that is broadcasted to lots of people '},
                 { u'feedback': u'If it were easy, you wouldn\u2019t be learning anything!',
                   u'score': 0.0,
                   u'text': u'd. a shared texting account on Verizon or AT&T '}],
    'cspcode': '0.0.0X',
    'description': u'Broadcast Hub Definition',
    'permute': False,
    'question': u'A broadcast hub is __________________.\n',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Innovation and its purpose well described'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Adequate but with weaknesses'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Poorly described'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'Missing'}],
    'cspcode': '0.0.0X',
    'description': u'EPT - Innovation Description',
    'question': u'Innovation Description - Report includes the innovation name and a description of the intended purpose of the innovation.',
    'source': 'mcsp-',
    'type': 0},
  { 'cspcode': '0.0.0X',
    'description': u'EPT1 - Directions',
    'graders': [ { u'feedback': u'Thank you for submitting! ',
                   u'matcher': u'regex',
                   u'response': u'/.*/i',
                   u'score': u'36'}],
    'hint': u'',
    'question': u'<h2 style="font-size: 18px;"><span style="font-size: 13px; font-weight: normal; color: rgb(68, 68, 68); line-height: 20.0200004577637px; font-family: arial, sans-serif;">Please review the official proposed <a href="https://drive.google.com/open?id=0B5ZVxaK8f0u9cXRneVNpcUZoUEU" target="_blank">Explore Performance Task Fall 2015 Version</a> </span><span class="yui-tag-span yui-tag" tag="span" style="color: rgb(255, 0, 0); font-size: 13px; font-family: arial, sans-serif;">(effective as of 12/01/2015)&nbsp;</span><span style="font-size: 13px; font-weight: normal; color: rgb(68, 68, 68); font-family: arial, sans-serif; line-height: 20.0200004577637px;">from the College Board. [Note: Looking for the old version? <a href="https://drive.google.com/folderview?id=0B86iRIPU8oQlfmJrWlNzS2Y1MlRMZ2V1RHAwMXlJUTBBazdnSGFGWDBGTGpBbnNUSVVadEE&usp=sharing" target="_blank">Try here</a>.]\n\nYou should carefully review all of the directions as presented by the College Board and will need to address the requirements and prompts as outlined in the Performance Task directions. This assignment is a practice for the official task. For the official Explore Performance Task #2, you will have to choose your own topic.</span>\n\n</h2><h2 style="font-size: 18px;">Overview<br></h2>\n<p>Computing innovations have had considerable impact on the social, economic and cultural areas of our lives. One example is sexting and phone monitoring software which has had significant impact on our society and has had both beneficial and harmful effects. For this task, read <a href="https://drive.google.com/file/d/0B5ZVxaK8f0u9NWpuMFBVOFpqSlk/view?usp=sharing" target="_blank">this article</a>, then install and examine one of the phone monitoring apps listed below. You will do the following:<br></p><ul><li><span style="line-height: 1.22;">Produce a written response that explains the ethics of phone monitoring software (including the app you selected). Your written response should discuss the impact that phone monitoring software has on our society and convey a deep level of additional understanding of mobile app technologies.&nbsp;</span></li><li><span style="line-height: 1.22;">Produce and submit an original visual artifact that illustrates the effect of phone monitoring software.</span><br></li><li><span style="line-height: 1.22;">Produce written support for your artifact</span></li></ul><br><b style="line-height: 1.22;">Phone monitoring apps</b><span style="line-height: 1.22;"> (pick </span><b style="line-height: 1.22;"><u>one</u></b><span style="line-height: 1.22;"> of the following):</span><br><p></p>\n<ul>\n<li><a href="http://www.teensafe.com/#slide2" target="_blank">Teen Safe\n</a></li><li><a href="https://www.mymobilewatchdog.com/signup.shtml" target="_blank">Mobile Watchdog\n</a></li><li><a href="http://www.mobile-spy.com/android.html" target="_blank">Mobile Spy\n</a></li><li><a href="http://www.netnanny.com/mobile" target="_blank">Net Nanny\n</a></li>\n</ul>\n\n<span class="yui-tag-span yui-tag" tag="span"><span style="color: rgb(68, 68, 68); font-size: 15px; line-height: 1.22;"><br><b>A. General Requirements</b></span><span style="color: rgb(68, 68, 68); font-size: 15px; line-height: 1.22;"><br></span></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Select a computing innovation to investigate that has had a significant impact on society, economy, or&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">culture. You must be able to convey an understanding of the innovation by discussing the relationship of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">the innovation to the principles of computer science, particularly the role data plays and the&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">cybersecurity issues that exist. You will then address specific prompts that call for either a written&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">response or a visual/audio response.&nbsp;<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">For this task, you will include at least three references/citations to sources used to formulate your&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">written responses.&nbsp;<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022 Each source must be a reliable newspaper/magazine article, book, news,&nbsp;or online source that&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">anyone can access.<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022 For each reference, provide the full citation identifying the author, title,&nbsp;source, and, if possible,&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">the date the reference was written or posted. You&nbsp;will <br><span class="Apple-tab-span" style="white-space:pre">\t</span>&nbsp;&nbsp;list these citations at the end of your&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Written Responses submission.<br></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022 For online references, include the permanent URL and the date on which&nbsp;you accessed the&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">reference.<br></span><span style="line-height: 1.22; font-size: 13px; font-weight: normal;"><span class="Apple-tab-span" style="white-space:pre">\t</span>\u2022&nbsp;At least two of the sources must have been created after the end of the&nbsp;previous academic year.</span><p></p><ul>\n</ul>\n\n<p><span class="yui-tag-span yui-tag" tag="span" style="font-size: 15px;"><b>B. Written Requirements</b></span><br><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Submit one PDF document. Your responses to the following prompts must convey a deep level of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">understanding about your chosen innovation and its impact(s). Respond directly to each prompt and&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">clearly label your responses (a, b, c, d, e, f, g, h). Cite information from the reference(s) you used to&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">respond to prompts b, c, d, e, f, g, h.</span><span style="font-size: 13px; line-height: 1.22;"> You have a maximum of 200 words for each response.</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span><b>Purpose<br></b></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>a. Indicate the name of the innovation and provide a clear description of its intended purpose (such&nbsp;</span><span style="line-height: 1.22;">as&nbsp;the problem that the innovation solved, the &nbsp;&nbsp;<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>opportunity that the innovation created, or the&nbsp;</span><span style="line-height: 1.22;">discovery&nbsp;that the innovation made possible).&nbsp;</span></p><p><span style="line-height: 1.22;"><b><span class="Apple-tab-span" style="white-space:pre">\t</span>Effects and Impacts<br></b></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>b. Explain a benefit and/or harmful effect of the innovation.<span class="Apple-tab-span" style="white-space:pre">\t</span><br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>c. Explain an impact the innovation has had, or has the potential to have, on society, economy,&nbsp;</span><span style="line-height: 1.22;">and/or&nbsp;culture.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>d. Indicate one field, other than computer science, which this innovation has impacted or has&nbsp;</span><span style="line-height: 1.22;">the&nbsp;</span><span style="line-height: 1.22;">potential to impact. Describe the impact.</span></p><p><span style="line-height: 1.22;"><b><span class="Apple-tab-span" style="white-space:pre">\t</span>Technical Aspects<br></b></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>When writing your responses, use language that would be understandable to someone who is&nbsp;not&nbsp;</span><span style="line-height: 1.22;">familiar with the innovation.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>e. Describe how a user interacts with the innovation.&nbsp;<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>f. Describe in detail how the innovation\'s technology incorporates at least ONE of the big ideas of&nbsp;</span><span style="line-height: 1.22;">abstraction, algorithms, programming, and/or the&nbsp;<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Internet to accomplish its purpose.</span></p><p><b style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Relationship to Data<br></b><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Discuss the role data plays in your chosen innovation by responding to each of the following:<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>g. Describe how the innovation consumes data (as input), produces data (as output), and/or&nbsp;</span><span style="line-height: 1.22;">transforms data.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>h. Describe at least one data storage concern, privacy concern, or security concern related to the&nbsp;</span><span style="line-height: 1.22;">innovation.</span></p><ul>\n</ul>\n\n<p><span class="yui-tag-span yui-tag" tag="span" style="font-size: 15px;"><b>C. Artifact</b></span><br><span class="yui-tag-span yui-tag" tag="span" style="font-size: 13px; font-weight: normal;">Use computing tools and techniques to create one original visual or audio artifact (a visualization,</span>&nbsp;<span style="font-size: 13px; font-weight: normal; line-height: 1.22;">graphic, video, or audio recording) that elaborates and/or highlights a different and/or deeper aspect of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">the innovation than you provided in your written responses. Submit as a PDF (3 pages maximum), video&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">or audio file (1 minute maximum length and 30 mb maximum size). Acceptable multimedia file types&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">include mp4, wmv, avi, or mov format.</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>Your artifact must satisfy ONE of the following requirements:</span></p><p></p><ul><li><span style="line-height: 1.22;">&nbsp; Provide insight into a beneficial and/or harmful effect of the innovation.&nbsp;</span><br></li><li><span style="line-height: 1.22;">&nbsp; Illustrate and/or describe an impact of the innovation on society, economy, and/or culture.</span><br></li></ul><p></p><ul>\n</ul>\n\n<p><span class="yui-tag-span yui-tag" tag="span" style="font-size: 15px;"><b>D. Written Support for Artifact</b></span><br><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">Submit one PDF document. Your responses to the following prompts must convey a deep level of&nbsp;</span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;">understanding about your artifact. Clearly label your responses (a, b). <b>You have a maximum of 200&nbsp;</b></span><span style="font-size: 13px; font-weight: normal; line-height: 1.22;"><b>words for each response.</b></span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>a. Explain how your artifact elaborates or highlights a different and/or deeper aspect of the&nbsp;</span><span style="line-height: 1.22;">innovation than you provided in your written responses.<br><span class="Apple-tab-span" style="white-space:pre">\t</span>&nbsp; &nbsp; Demonstrate that your artifact&nbsp;</span><span style="line-height: 1.22;">accomplished ONE of the following requirements:&nbsp;</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t\t</span>\u2022 Provided insight into a beneficial and/or harmful effect of the innovation.<br></span><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t\t</span>\u2022 Illustrated or describe an impact of the innovation on society, economy, and/or culture.&nbsp;</span></p><p><span style="line-height: 1.22;"><span class="Apple-tab-span" style="white-space:pre">\t</span>b. Clearly describe the computing tools, techniques, and development process that you used to&nbsp;</span><span style="line-height: 1.22;">create your artifact. Your description must be clear<br><span class="Apple-tab-span" style="white-space:pre">\t</span>&nbsp;&nbsp; &nbsp;enough so that someone can read your&nbsp;</span><span style="line-height: 1.22;">description and reproduce the artifact.</span></p><ul>\n</ul>\n\n<h2>Grading Rubric</h2>\nYour project will be graded based on the documents you submit on your portfolio. Your project will be graded using this <a href="https://drive.google.com/open?id=0B5ZVxaK8f0u9RlFVY3NaY0UzUlE" target="_blank">Explore Performance Task Rubric Fall 2015 Version</a> </span><span class="yui-tag-span yui-tag" tag="span" style="color: rgb(255, 0, 0); font-size: 13px; font-family: arial, sans-serif;">(effective as of 12/01/2015)&nbsp;</span><span style="font-size: 13px; font-weight: normal; color: rgb(68, 68, 68); font-family: arial, sans-serif; line-height: 20.0200004577637px;">from the College Board. [Note: Looking for the old version? <a href="https://drive.google.com/folderview?id=0B86iRIPU8oQlfmJrWlNzS2Y1MlRMZ2V1RHAwMXlJUTBBazdnSGFGWDBGTGpBbnNUSVVadEE&usp=sharing" target="_blank">Try here</a>.]\n\n<table width="100%" style="margin:auto;">\n  <tbody><tr>\n    <th style="width:25%">Aspect</th>\n    <th style="width:25%">Learning Objectives</th>\n    <th style="width:50%">Performance Quality</th>\n  </tr>\n\n\n  <tr>\n    <td>Written Responses </td>\n    <td>7.1.1</td>\n    <td>The innovation\u2019s name and intended purpose are described in detail.</td>\n\n  </tr>\n\n\n  <tr>\n    <td></td>\n    <td>7.1.1<br>7.2.1<br>7.3.1<br>7.4.1</td>\n    <td>The response analyzes the innovation\u2019s beneficial and harmful effects and describes, in depth, its overall impact on society and its potential impact in a field other than computer science.</td>\n\n  </tr>\n\n  <tr>\n    <td></td>\n    <td> 1.2.5</td>\n    <td>The response fully explains how a user interacts with the innovation and provides a comprehensive explanation of the relationship of the innovation\u2019s purpose to one or more of the big ideas of the course.</td>\n\n  </tr>\n\n  <tr>\n    <td><br></td>\n    <td>3.3.1<br>7.3.1<br>7.4.1</td>\n    <td>The response analyzes how the innovation consumes data (as input), produces data (as output), and/or transforms data. The response also explains a concern related to data storage, privacy, or security.</td>\n\n  </tr>\n\n  <tr>\n    <td></td>\n    <td> 1.2.5</td>\n    <td>There is a compelling connection between the program and its stated purpose. and describes the required input and generated output.</td>\n\n</tr>\n\n  <tr>\n    <td>Artifact </td>\n    <td>1.2.1<br>1.2.2<br>1.2.3</td>\n    <td>The artifact extends the information supplied in the written responses. Previously published or   developed work contributes to, or supports, the production of an original artifact, or all of the work in the artifact appears to be original.</td>\n\n  </tr>\n\n    <tr>\n    <td></td>\n    <td>7.1.1<br>7.2.1<br>7.3.1<br>7.4.1</td>\n    <td>The artifact provides deep insight by explaining in explicit detail the beneficial or harmful effects of the innovation or convincingly illustrating its impact on society.</td>\n\n  </tr>\n  \n    <tr>\n    <td>Written Support for Artifact</td>\n    <td>7.1.1<br>7.2.1<br>7.3.1<br>7.4.1</td>\n    <td>The written support provides details that explain and extend the information supplied in the artifact about potential beneficial or harmful effects of the innovation or its impact on society.</td>\n  </tr>\n\n  <tr>\n    <td></td>\n    <td>1.2.2<br>1.2.3<br>1.2.5\n    </td><td>The written support clearly and comprehensively describes the computing tools, techniques, and development process used to create the artifact.</td>\n\n\n  </tr>\n\n\n</tbody></table>\n\n<h2>Submitting</h2>\n<p>Upload your PDF write-up and visual artifact to your portfolio. Submit the URL of your performance task on your portfolio. One pdf, video, or audio per student. (Example: http://www.mysite.com/exploreperformancetaskwriteup.<b>pdf</b>)</p>',
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u'URL for the Explore Performance Task page of your portfolio:<br>\nExample: http://www.mysite.com/project1writeup.html'},
  { 'choices': [ { u'feedback': u'', u'score': 0.25, u'text': u'Twitter'},
                 { u'feedback': u'Mistakes are welcome here! ',
                   u'score': -1.0,
                   u'text': u'Excel'},
                 { u'feedback': u'', u'score': 0.25, u'text': u'G-mail'},
                 { u'feedback': u'Mistakes are welcome here! ',
                   u'score': -1.0,
                   u'text': u'PowerPoint'},
                 { u'feedback': u'', u'score': 0.25, u'text': u'Facebook'},
                 { u'feedback': u'', u'score': 0.25, u'text': u'Dropbox'}],
    'cspcode': '0.0.0X',
    'description': u'Cloud Computing Applications Examples',
    'permute': False,
    'question': u'Which of the following is an example of a cloud computing application? <br>\n<b>Choose all that apply. </b>',
    'source': 'mcsp-',
    'type': 0,
    'wrongfeedback': u''},
  { 'cspcode': '0.0.0X',
    'description': u'Breaking Caesar with frequency analysis',
    'graders': [ { u'feedback': u"That's right! The secret word is <i><b>awesome</i></b>. Given the information that the most frequent letter was the letter 'i', you would figure that the shift used in this case was 4. That means that 'a' is encrypted as 'e' and 'w' is encrypted as 'a', and 'e' is encrypted as 'i', and so on. Proceeding in this way you can break the cipher.",
                   u'matcher': u'case_insensitive',
                   u'response': u'awesome',
                   u'score': u'1.0'}],
    'hint': u"Remember that 'e' is the most frequent letter ",
    'question': u"Suppose that the following word, <i><b>EAIWSQI</b></i>, was encrypted with a Caesar cipher and when you do a frequency analysis you learn that the most frequent letter was 'i'. What is the secret word? Type your answer into the Textbox.  (Make sure there are no extra spaces in your answer.) ",
    'source': 'mcsp-',
    'type': 1,
    'wrongfeedback': u''},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Very well documented'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Fairly well documented \u2013 some problems'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Not well documented \u2013 no comments/poor names '},
                 { u'feedback': u'',
                   u'score': 0.0,
                   u'text': u'Did not complete'}],
    'cspcode': '0.0.0X',
    'description': u'CP2 - Documentation of Code',
    'question': u'Documentation of Code',
    'source': 'mcsp-',
    'type': 0},
  { 'choices': [ { u'feedback': u'',
                   u'score': 3.0,
                   u'text': u'Population well described'},
                 { u'feedback': u'',
                   u'score': 2.0,
                   u'text': u'Group or its importance not clear'},
                 { u'feedback': u'',
                   u'score': 1.0,
                   u'text': u'Population impacted by innovation is not clear'},
                 { u'feedback': u'', u'score': 0.0, u'text': u'Missing'}],
    'cspcode': '0.0.0X',
    'description': u'EPT - Impacted Population',
    'question': u'Impacted Population - Report describes the population that is impacted by the innovation, including population characteristics such as approximate size, socioeconomic status, geographic location, health, age, gender, ethnicity, race, sexual orientation, and disability.',
    'source': 'mcsp-',
    'type': 0}];